package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Негативный сценарий. Аутентификация пользователя через номер карты.")
    void generatedTest() {
        step("Open https://online.vtb.ru/login", () -> {
            step("// todo: just add selenium action");
        });

        step("Click", () -> {
            step("// todo: just add selenium action");
        });

        step("Type", () -> {
            step("// todo: just add selenium action");
        });

        step("Should be visible", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://online.vtb.ru/login'", () ->
            open("https://online.vtb.ru/login"));

        step("Page title should have text 'Интернет-банк ВТБ Онлайн: вход в личный кабинет'", () -> {
            String expectedTitle = "Интернет-банк ВТБ Онлайн: вход в личный кабинет";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://online.vtb.ru/login'", () ->
            open("https://online.vtb.ru/login"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}